name: Node.js Package

on:
  release:
    types: [created]

jobs:
  send-sms:
    name: Send SMS
    runs-on: ubuntu-latest
    steps:
    - name: smsalert
      uses: SMSAlert/smsalert@1.0.0
      with:
         # senderid in your SMSAlert account to send the SMS from
        senderid: ${{ secrets.senderid }}
        # Phone number to send the SMS to
        toPhoneNumber: ${{ secrets.toPhoneNumber }}
        # The message you want to send
        message: 'hello'
        # A SMSAlert Username. Can alternatively be stored in environment
        SMSALERT_USERNAME: ${{ secrets.SMSALERT_USERNAME }}
        # A SMSAlert Password. Can alternatively be stored in environment
        SMSALERT_PASSWORD: ${{ secrets.SMSALERT_PASSWORD }}

